/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DenahRouteImport } from './routes/denah'
import { Route as FasilitasRouteImport } from './routes/fasilitas'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as PendapatanRouteImport } from './routes/pendapatan'
import { Route as PengeluaranRouteImport } from './routes/pengeluaran'
import { Route as KamarIndexRouteImport } from './routes/kamar.index'
import { Route as KamarNomorRouteImport } from './routes/kamar.$nomor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenahRoute = DenahRouteImport.update({
  id: '/denah',
  path: '/denah',
  getParentRoute: () => rootRouteImport,
} as any)
const FasilitasRoute = FasilitasRouteImport.update({
  id: '/fasilitas',
  path: '/fasilitas',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const PendapatanRoute = PendapatanRouteImport.update({
  id: '/pendapatan',
  path: '/pendapatan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengeluaranRoute = PengeluaranRouteImport.update({
  id: '/pengeluaran',
  path: '/pengeluaran',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarIndexRoute = KamarIndexRouteImport.update({
  id: '/kamar/',
  path: '/kamar/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarNomorRoute = KamarNomorRouteImport.update({
  id: '/kamar/$nomor',
  path: '/kamar/$nomor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denah': typeof DenahRoute
  '/fasilitas': typeof FasilitasRoute
  '/laporan': typeof LaporanRoute
  '/pendapatan': typeof PendapatanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/kamar/$nomor': typeof KamarNomorRoute
  '/kamar/': typeof KamarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denah': typeof DenahRoute
  '/fasilitas': typeof FasilitasRoute
  '/laporan': typeof LaporanRoute
  '/pendapatan': typeof PendapatanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/kamar/$nomor': typeof KamarNomorRoute
  '/kamar': typeof KamarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/denah': typeof DenahRoute
  '/fasilitas': typeof FasilitasRoute
  '/laporan': typeof LaporanRoute
  '/pendapatan': typeof PendapatanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/kamar/$nomor': typeof KamarNomorRoute
  '/kamar/': typeof KamarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/denah'
    | '/fasilitas'
    | '/laporan'
    | '/pendapatan'
    | '/pengeluaran'
    | '/kamar/$nomor'
    | '/kamar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/denah'
    | '/fasilitas'
    | '/laporan'
    | '/pendapatan'
    | '/pengeluaran'
    | '/kamar/$nomor'
    | '/kamar'
  id:
    | '__root__'
    | '/'
    | '/denah'
    | '/fasilitas'
    | '/laporan'
    | '/pendapatan'
    | '/pengeluaran'
    | '/kamar/$nomor'
    | '/kamar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DenahRoute: typeof DenahRoute
  FasilitasRoute: typeof FasilitasRoute
  LaporanRoute: typeof LaporanRoute
  PendapatanRoute: typeof PendapatanRoute
  PengeluaranRoute: typeof PengeluaranRoute
  KamarNomorRoute: typeof KamarNomorRoute
  KamarIndexRoute: typeof KamarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denah': {
      id: '/denah'
      path: '/denah'
      fullPath: '/denah'
      preLoaderRoute: typeof DenahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasilitas': {
      id: '/fasilitas'
      path: '/fasilitas'
      fullPath: '/fasilitas'
      preLoaderRoute: typeof FasilitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendapatan': {
      id: '/pendapatan'
      path: '/pendapatan'
      fullPath: '/pendapatan'
      preLoaderRoute: typeof PendapatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengeluaran': {
      id: '/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/pengeluaran'
      preLoaderRoute: typeof PengeluaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar/': {
      id: '/kamar/'
      path: '/kamar'
      fullPath: '/kamar/'
      preLoaderRoute: typeof KamarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar/$nomor': {
      id: '/kamar/$nomor'
      path: '/kamar/$nomor'
      fullPath: '/kamar/$nomor'
      preLoaderRoute: typeof KamarNomorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DenahRoute: DenahRoute,
  FasilitasRoute: FasilitasRoute,
  LaporanRoute: LaporanRoute,
  PendapatanRoute: PendapatanRoute,
  PengeluaranRoute: PengeluaranRoute,
  KamarNomorRoute: KamarNomorRoute,
  KamarIndexRoute: KamarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
